### ISSUE TITLE
variable @scrollbar-background-color is undefined

### ISSUE THREAD

**Issue by basarat** [atom/base16-tomorrow-light-theme#2]
I've been forced to customize the css for scroll bars in a panel in my package: [source](https://github.com/TypeStrong/atom-typescript/blob/10edf6f0565ecd6a558b77e9fb0102beee035425/stylesheets/documentationview.less#L24-L37)

```less
    ::-webkit-scrollbar {
        width: 8px;
        height: 8px;
     }
     ::-webkit-scrollbar-track,
     ::-webkit-scrollbar-corner {
         background: @scrollbar-background-color;
     }
    ::-webkit-scrollbar-thumb {
        background: @scrollbar-color;
        border-radius: 5px;
        box-shadow: 0 0 1px black inset;
    }
```
Requested guidance here : https://discuss.atom.io/t/ugly-scroll-bar-in-package/14989.

However with the light theme I get the error : 
```
Error compiling Less stylesheet:
C:\Users\basaratsyed\.atom\packages\atom-typescript\stylesheets\documentationview.less
Line number: 33
variable @scrollbar-background-color is undefined
```

Screenshot : 
![image](https://cloud.githubusercontent.com/assets/874898/6321901/823ac160-bb5c-11e4-915c-12750f0c0808.png)

**Doesn't happen in the dark theme**

I don't seem to find `@scrollbar-background-color` defined specifically in the dark theme : https://github.com/atom/base16-tomorrow-dark-theme so would be great if you could point me to it.

refs https://github.com/TypeStrong/atom-typescript/issues/120
Original source of LESS : https://github.com/atom/atom/blob/master/docs/upgrading/upgrading-your-ui-theme.md#deep
